// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	domain "github.com/junminhong/member-center-service/domain"

	mock "github.com/stretchr/testify/mock"

	responser "github.com/junminhong/member-center-service/pkg/responser"
)

// MemberUseCase is an autogenerated mock type for the MemberUseCase type
type MemberUseCase struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, member
func (_m *MemberUseCase) Register(ctx *gin.Context, member *domain.Member) responser.Response {
	ret := _m.Called(ctx, member)

	var r0 responser.Response
	if rf, ok := ret.Get(0).(func(*gin.Context, *domain.Member) responser.Response); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Get(0).(responser.Response)
	}

	return r0
}
